<a href="https://colab.research.google.com/github/Shaikhabdulh/RAG_Pipline/blob/main/RAG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

# Download Requirement File for Project & Install Packeges

In [ ]:
import os
import requests

requirement_path = "requirements.txt"

if not os.path.exists(requirement_path):
  print(f"[INFO] File Doesn't Exists, Downloading....")

  # Enter the URL of the PDF
  url = "https://drive.usercontent.google.com/download?id=1OTMlfeLLTQO6lxNG3cxf0syf99ENWIoA&export=download&authuser=0"

  # The Local Filename to save the downloading file
  filename= requirement_path

  # Send a get request to the url
  response = requests.get(url)

  # Check if the request was successful
  if response.status_code == 200:

  # Save the content of the request to the local file
    with open(filename, 'wb') as f:
      f.write(response.content)
    print(f"[INFO] The File has been downloaded and saved as {filename}")
  else:
      print(f"[INFO] Failed to download the file. Status code: {response.status_code}")

else:
  print(f"File {requirement_path} exists.")

[INFO] File Doesn't Exists, Downloading....
[INFO] The File has been downloaded and saved as requirements.txt

In [ ]:
!pip install -r ./requirements.txt --upgrade --force-reinstall --no-cache-dir

Collecting PyMuPDF==1.23.26 (from -r ./requirements.txt (line 1))
  Downloading PyMuPDF-1.23.26-cp311-none-manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting matplotlib==3.8.3 (from -r ./requirements.txt (line 2))
  Downloading matplotlib-3.8.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting numpy==1.26.4 (from -r ./requirements.txt (line 3))
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 18.4 MB/s eta 0:00:00
Collecting pandas==2.2.1 (from -r ./requirements.txt (line 4))
  Downloading pandas-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting Requests==2.31.0 (from -r ./requirements.txt (line 5))
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting sentence_transformers==2.5.1 (from -r ./requirements.txt (line 6))
  Downloading sentence_transformers-2.5.1-py3-none-any.whl.metadata (11 kB)
Collecting spacy (from -r ./requirements.txt (line 7))
  Downloading spacy-3.8.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting tqdm==4.66.2 (from -r ./requirements.txt (line 8))
  Downloading tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 71.2 MB/s eta 0:00:00
Collecting transformers==4.38.2 (from -r ./requirements.txt (line 9))
  Downloading transformers-4.38.2-py3-none-any.whl.metadata (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.7/130.7 kB 20.0 MB/s eta 0:00:00
Collecting accelerate (from -r ./requirements.txt (line 10))
  Downloading accelerate-1.9.0-py3-none-any.whl.metadata (19 kB)
Collecting bitsandbytes (from -r ./requirements.txt (line 11))
  Downloading bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting jupyter (from -r ./requirements.txt (line 12))
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting wheel (from -r ./requirements.txt (line 13))
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting PyMuPDFb==1.23.22 (from PyMuPDF==1.23.26->-r ./requirements.txt (line 1))
  Downloading PyMuPDFb-1.23.22-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading fonttools-4.59.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.9/107.9 kB 238.8 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading kiwisolver-1.4.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.2 kB)
Collecting packaging>=20.0 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pillow>=8 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Collecting pyparsing>=2.3.1 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Collecting python-dateutil>=2.7 (from matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.2.1->-r ./requirements.txt (line 4))
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.2.1->-r ./requirements.txt (line 4))
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting charset-normalizer<4,>=2 (from Requests==2.31.0->-r ./requirements.txt (line 5))
  Downloading charset_normalizer-3.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from Requests==2.31.0->-r ./requirements.txt (line 5))
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from Requests==2.31.0->-r ./requirements.txt (line 5))
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from Requests==2.31.0->-r ./requirements.txt (line 5))
  Downloading certifi-2025.7.14-py3-none-any.whl.metadata (2.4 kB)
Collecting torch>=1.11.0 (from sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading torch-2.7.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting scikit-learn (from sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading scikit_learn-1.7.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Collecting scipy (from sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading scipy-1.16.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 195.3 MB/s eta 0:00:00
Collecting huggingface-hub>=0.15.1 (from sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading huggingface_hub-0.34.3-py3-none-any.whl.metadata (14 kB)
Collecting filelock (from transformers==4.38.2->-r ./requirements.txt (line 9))
  Downloading filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting pyyaml>=5.1 (from transformers==4.38.2->-r ./requirements.txt (line 9))
  Downloading PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting regex!=2019.12.17 (from transformers==4.38.2->-r ./requirements.txt (line 9))
  Downloading regex-2025.7.34-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.5/40.5 kB 227.6 MB/s eta 0:00:00
Collecting tokenizers<0.19,>=0.14 (from transformers==4.38.2->-r ./requirements.txt (line 9))
  Downloading tokenizers-0.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers==4.38.2->-r ./requirements.txt (line 9))
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy->-r ./requirements.txt (line 7))
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy->-r ./requirements.txt (line 7))
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy->-r ./requirements.txt (line 7))
  Downloading murmurhash-1.0.13-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.2 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy->-r ./requirements.txt (line 7))
  Downloading cymem-2.0.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.5 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy->-r ./requirements.txt (line 7))
  Downloading preshed-3.0.10-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.4 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy->-r ./requirements.txt (line 7))
  Downloading thinc-8.3.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy->-r ./requirements.txt (line 7))
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy->-r ./requirements.txt (line 7))
  Downloading srsly-2.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy->-r ./requirements.txt (line 7))
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy->-r ./requirements.txt (line 7))
  Downloading weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting typer<1.0.0,>=0.3.0 (from spacy->-r ./requirements.txt (line 7))
  Downloading typer-0.16.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy->-r ./requirements.txt (line 7))
  Downloading pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.0/68.0 kB 165.0 MB/s eta 0:00:00
Collecting jinja2 (from spacy->-r ./requirements.txt (line 7))
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting setuptools (from spacy->-r ./requirements.txt (line 7))
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy->-r ./requirements.txt (line 7))
  Downloading langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
Collecting psutil (from accelerate->-r ./requirements.txt (line 10))
  Downloading psutil-7.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting notebook (from jupyter->-r ./requirements.txt (line 12))
  Downloading notebook-7.4.4-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter->-r ./requirements.txt (line 12))
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter->-r ./requirements.txt (line 12))
  Downloading nbconvert-7.16.6-py3-none-any.whl.metadata (8.5 kB)
Collecting ipykernel (from jupyter->-r ./requirements.txt (line 12))
  Downloading ipykernel-6.30.0-py3-none-any.whl.metadata (6.2 kB)
Collecting ipywidgets (from jupyter->-r ./requirements.txt (line 12))
  Downloading ipywidgets-8.1.7-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab (from jupyter->-r ./requirements.txt (line 12))
  Downloading jupyterlab-4.4.5-py3-none-any.whl.metadata (16 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.15.1->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading fsspec-2025.7.0-py3-none-any.whl.metadata (12 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub>=0.15.1->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub>=0.15.1->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading hf_xet-1.1.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (879 bytes)
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy->-r ./requirements.txt (line 7))
  Downloading language_data-1.3.0-py3-none-any.whl.metadata (4.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->-r ./requirements.txt (line 7))
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->-r ./requirements.txt (line 7))
  Downloading pydantic_core-2.33.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting typing-inspection>=0.4.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->-r ./requirements.txt (line 7))
  Downloading typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib==3.8.3->-r ./requirements.txt (line 2))
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy->-r ./requirements.txt (line 7))
  Downloading blis-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy->-r ./requirements.txt (line 7))
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
INFO: pip is looking at multiple versions of thinc to determine which version is compatible with other requirements. This could take a while.
Collecting thinc<8.4.0,>=8.3.4 (from spacy->-r ./requirements.txt (line 7))
  Downloading thinc-8.3.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting blis<1.3.0,>=1.2.0 (from thinc<8.4.0,>=8.3.4->spacy->-r ./requirements.txt (line 7))
  Downloading blis-1.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.5.1.17 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.6.4.1 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.3.0.4 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.7.77 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.7.1.2 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.4.2 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.3 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.26.2 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.6.77 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nvjitlink-cu12==12.6.85 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufile-cu12==1.11.1.6 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.3.1 (from torch>=1.11.0->sentence_transformers==2.5.1->-r ./requirements.txt (line 6))
  Downloading triton-3.3.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Collecting click>=8.0.0 (from typer<1.0.0,>=0.3.0->spacy->-r ./requirements.txt (line 7))
  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy->-r ./requirements.txt (line 7))
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer<1.0.0,>=0.3.0->spacy->-r ./requirements.txt (line 7))
  Downloading rich-14.1.0-py3-none-any.whl.metadata (18 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy->-r ./requirements.txt (line 7))
  Downloading cloudpathlib-0.21.1-py3-none-any.whl.metadata (14 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.1.0->spacy->-r ./requirements.txt (line 7))
  Downloading smart_open-7.3.0.post1-py3-none-any.whl.metadata (24 kB)
Collecting comm>=0.1.1 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading comm-0.2.3-py3-none-any.whl.metadata (3.7 kB)
Collecting debugpy>=1.6.5 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading debugpy-1.8.15-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting ipython>=7.23.1 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading ipython-9.4.0-py3-none-any.whl.metadata (4.4 kB)
Collecting jupyter-client>=8.0.0 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading jupyter_client-8.6.3-py3-none-any.whl.metadata (8.3 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading jupyter_core-5.8.1-py3-none-any.whl.metadata (1.6 kB)
Collecting matplotlib-inline>=0.1 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading matplotlib_inline-0.1.7-py3-none-any.whl.metadata (3.9 kB)
Collecting nest-asyncio>=1.4 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting pyzmq>=25 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading pyzmq-27.0.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.0 kB)
Collecting tornado>=6.2 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading tornado-6.5.1-cp39-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.8 kB)
Collecting traitlets>=5.4.0 (from ipykernel->jupyter->-r ./requirements.txt (line 12))
  Downloading traitlets-5.14.3-py3-none-any.whl.metadata (10 kB)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets->jupyter->-r ./requirements.txt (line 12))
  Downloading widgetsnbextension-4.0.14-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets->jupyter->-r ./requirements.txt (line 12))
  Downloading jupyterlab_widgets-3.0.15-py3-none-any.whl.metadata (20 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy->-r ./requirements.txt (line 7))
  Downloading MarkupSafe-3.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting prompt-toolkit>=3.0.30 (from jupyter-console->jupyter->-r ./requirements.txt (line 12))
  Downloading prompt_toolkit-3.0.51-py3-none-any.whl.metadata (6.4 kB)
Collecting pygments (from jupyter-console->jupyter->-r ./requirements.txt (line 12))
  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter->-r ./requirements.txt (line 12))
  Downloading async_lru-2.0.5-py3-none-any.whl.metadata (4.5 kB)

In [ ]:
!pip uninstall numpy pandas -y
!pip install numpy pandas --upgrade --force-reinstall --no-cache-dir

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: pandas 2.2.1
Uninstalling pandas-2.2.1:
  Successfully uninstalled pandas-2.2.1
Collecting numpy
  Downloading numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 3.7 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 25.0 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.2 (from pandas)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 87.8 MB/s eta 0:00:00
Downloading pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 128.5 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 217.3 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.2/509.2 kB 102.6 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.8/347.8 kB 224.8 MB/s eta 0:00:00
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.2
    Uninstalling pytz-2025.2:
      Successfully uninstalled pytz-2025.2
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2025.2
    Uninstalling tzdata-2025.2:
      Successfully uninstalled tzdata-2025.2
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.8.3 requires numpy<2,>=1.21, but you have numpy 2.3.2 which is incompatible.
google-colab 1.0.0 requires ipykernel==6.17.1, but you have ipykernel 6.30.0 which is incompatible.
google-colab 1.0.0 requires ipython==7.34.0, but you have ipython 9.4.0 which is incompatible.
google-colab 1.0.0 requires notebook==6.5.7, but you have notebook 7.4.4 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.1 which is incompatible.
google-colab 1.0.0 requires requests==2.32.3, but you have requests 2.31.0 which is incompatible.
google-colab 1.0.0 requires tornado==6.4.2, but you have tornado 6.5.1 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
cupy-cuda12x 13.3.0 requires numpy<2.3,>=1.22, but you have numpy 2.3.2 which is incompatible.
fastai 2.7.19 requires torch<2.7,>=1.10, but you have torch 2.7.1 which is incompatible.
torchvision 0.21.0+cu124 requires torch==2.6.0, but you have torch 2.7.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
jupyter-kernel-gateway 2.5.2 requires jupyter-client<8.0,>=5.2.0, but you have jupyter-client 8.6.3 which is incompatible.
jupyter-kernel-gateway 2.5.2 requires notebook<7.0,>=5.7.6, but you have notebook 7.4.4 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.1 which is incompatible.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2025.7.0 which is incompatible.
datasets 4.0.0 requires requests>=2.32.2, but you have requests 2.31.0 which is incompatible.
datasets 4.0.0 requires tqdm>=4.66.3, but you have tqdm 4.66.2 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.3.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.2.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.2 which is incompatible.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
bigframes 2.12.0 requires rich<14,>=12.4.4, but you have rich 14.1.0 which is incompatible.
Successfully installed numpy-2.3.2 pandas-2.3.1 python-dateutil-2.9.0.post0 pytz-2025.2 six-1.17.0 tzdata-2025.2

## Now Download PDF File & Work on it

In [ ]:
import os
import requests

pdf_path = "Products.pdf"

if not os.path.exists(pdf_path):
  print(f"[INFO] File Doesn't Exists, Downloading....")

  # Enter the URL of the PDF
  url = "https://drive.usercontent.google.com/download?id=1etrZvWZUJhmi2PCvJxFVShsfZqK4_xh3&export=download&authuser=0"

  # The Local Filename to save the downloading file
  filename= pdf_path

  # Send a get request to the url
  response = requests.get(url)

  # Check if the request was successful
  if response.status_code == 200:

  # Save the content of the request to the local file
    with open(filename, 'wb') as f:
      f.write(response.content)
    print(f"[INFO] The File has been downloaded and saved as {filename}")
  else:
      print(f"[INFO] Failed to download the file. Status code: {response.status_code}")

else:
  print(f"File {pdf_path} exists.")

[INFO] File Doesn't Exists, Downloading....
[INFO] The File has been downloaded and saved as Products.pdf

In [ ]:
import fitz
from tqdm.auto import tqdm

def text_formatter(text: str) -> str:
  """Performs minor formatting on text."""
  cleaned_text = text.replace("\n"," ").strip()

# Potentially More text formatting functions can go here
  return cleaned_text

def open_and_read_pdf(pdf_path: str) -> list [dict]:
  doc = fitz.open(pdf_path)
  pages_and_texts = []
  for page_number, page in tqdm(enumerate(doc)):
    text = page.get_text()
    text = text_formatter(text=text)
    #if requires please minus and in my case i don't have any index page in my book so my book start with first page for real.
    # pages_and_texts.append({"page_number": page_number - your_pagenumber})
    pages_and_texts.append({"page_number": page_number,
                            "page_char_count": len(text),
                            "page_word_count": len(text.split(" ")),
                            "page_sentance_count_raw": len(text.split(". ")),
                            "page_token_count": len(text) / 4, # 1 token = ~4 characters.
                            "text": text})
  return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts [:2]

0it [00:00, ?it/s]

[{'page_number': 0,
  'page_char_count': 1258,
  'page_word_count': 190,
  'page_sentance_count_raw': 2,
  'page_token_count': 314.5,
  'text': 'Product Name:  Klik – Full Spectrum Extract  Formulation Overview:  A specialized medicinal formulation crafted using Ayurvedic principles, combining the full  therapeutic potential of Vijaya extract with other natural constituents.  Key Ingredients:  Vijaya Extract (Cannabis sativa full-spectrum)  (Other supporting actives not explicitly listed but aligned with Ayurvedic formulations)  Mechanism & Benefits:  Designed to support chronic discomfort, inflammatory conditions, and stress-related symptoms  Helps regulate sleep cycles  Aids in relaxation and emotional balance  Offers long-term wellness support through controlled dosing  Delivery Technology:  Utilizes Klik Dispense Technology – an oral syringe system for precise, single-dose  administration  Ensures measured and structured usage, especially for individuals requiring medical  supervision  Usage Suitability:  Ideal for:   Individuals with persistent physical discomfort   Stress and anxiety management   Sleep irregularities   Chronic inflammation  Also suitable for:   Regulated wellness routines   Long-term therapeutic use under guidance  Available Variants & Pricing:  Single Pack (1000μl): ₹2,599  Pack of 3: ₹7,020 (MRP: ₹7,797)  Pack of 6: ₹13,260 (MRP: ₹15,594)  Regulatory Note:'},
 {'page_number': 1,
  'page_char_count': 1215,
  'page_word_count': 195,
  'page_sentance_count_raw': 3,
  'page_token_count': 303.75,
  'text': 'Prescription-only product  Use strictly under supervision of a licensed medical practitioner  Product Name:  Pain Relief Mild Capsules  Formulation Overview:  A mild yet effective formulation designed for daily wellness support, containing 50mg of Vijaya  extract carefully blended with Ayurvedic ingredients.  Key Ingredients:  Vijaya extract (50mg)  Amla  Piperine  Mechanism & Benefits:  Assists in reducing inflammation  Promotes relaxation  Supports overall balance and general well-being  Helps manage chronic discomfort  Aids in stress regulation  Relieves muscle tension  May assist as a period aid (easing menstrual discomfort and cramping)  Supports the body’s natural inflammatory response  Offers a holistic and well-tolerated plant-based solution  Delivery Technology:  Capsule format, designed for structured use without disrupting daily activities.  Usage Suitability:  Ideal for:   Individuals seeking a gentle therapeutic approach   Managing chronic discomfort   Stress regulation   Muscle tension   General well-being   Period aid (easing menstrual discomfort and cramping)  Also suitable for:   Everyday Aches and Pains   Joint Pain and Stiffness   Stress-Related Muscle Tension   Headache Relief'}]

In [ ]:
#Just for testing
import random

random.sample(pages_and_texts, k=3)

[{'page_number': 5,
  'page_char_count': 1850,
  'page_word_count': 254,
  'page_sentance_count_raw': 17,
  'page_token_count': 462.5,
  'text': 'Aids in post-recovery care.  Offers a structured, well-regulated approach to long-term wellness.  Promotes sustained comfort and enhanced mobility.  Provides a natural and plant-based alternative.  Delivery Technology:  Capsule format.  Usage Suitability:  Ideal for individuals requiring targeted relief from persistent discomfort and mobility challenges.  Suitable for long-term wellness when a structured and well-regulated approach is needed.  Available Variants & Pricing:  Single Pack (2000mg variant): ₹1,499  Pack of 3: ₹4,050 (MRP: ₹4,497)  Regulatory Note:  Prescription-based formulation.  Available only with a valid prescription.  Use under medical supervision.  Cannacraft also provides guided consultations to help individuals access and integrate this  formulation responsibly.  Product Name:  Klik Gold- Full Spectrum Extract  Formulation Overview:  Cannacraft Klik Gold Full-Spectrum Extract is a highly concentrated medicinal formulation,  designed to provide targeted support for individuals requiring intensive relief. Developed under  Ayurvedic medicinal principles, this formulation harnesses the complete therapeutic potential of  the Vijaya plant, including its active compounds and naturally occurring botanical elements. This  synergy ensures a comprehensive and structured approach to managing persistent discomfort,  inflammation, nausea, appetite regulation, and sleep irregularities.  Engineered for measured precision, Klik Gold utilizes Klik Dispense Technology, delivering an  audible “click” for each precisely measured dose, ensuring accuracy, consistency, and controlled  administration. Designed for individuals managing complex health conditions, this  prescription-only formulation offers a structured and plant-based alternative under professional  supervision.  Key Ingredients:  Vijaya plant (full spectrum)'},
 {'page_number': 2,
  'page_char_count': 1205,
  'page_word_count': 204,
  'page_sentance_count_raw': 5,
  'page_token_count': 301.25,
  'text': 'Post-Workout Recovery   Mild Inflammatory Conditions   Women’s Health   Older Adults’ Mobility and Comfort   Immune System Support   Holistic Wellness  Available Variants & Pricing:  Single Pack (1000mg): ₹1,199  Pack Of 3: ₹3,240 (original price: ₹3,597)  Pack Of 6: ₹6,120 (original price: ₹7,194)  Regulatory Note:  For best results, use under the guidance of a licensed medical practitioner.  Product Name:  Xtra Gummies  Formulation Overview:  A high-strength formulation crafted for those who need more from plant-based relief. Each  gummy delivers 135mg of Vijaya leaf extract, offering approximately 30mg of total cannabinoids  (CBD + THC) for deep, balanced support. With 5 gummies per pack, Xtra is designed to ease  discomfort, calm the mind, and promote restful sleep - naturally, and powerfully.  Key Ingredients:  Vijaya leaf extract (135mg per gummy)  CBD:THC ratio: 1:1  Total Cannabinoids: ~30mg per Gummy  Mechanism & Benefits:  High-Potency Relief for Deep Calm  Pain Support  Restorative Sleep  Designed to ease discomfort, calm the mind, and promote restful sleep  Delivery Technology:  Gummy format  Usage Suitability:  High-Potency Vijaya Gummies for Deep Relief & Restorative Sleep'},
 {'page_number': 3,
  'page_char_count': 1425,
  'page_word_count': 230,
  'page_sentance_count_raw': 13,
  'page_token_count': 356.25,
  'text': 'Crafted for those who need more from plant-based relief  Available Variants & Pricing:  Single Pack: ₹1,499  Pack Of 3: ₹4,050 (MRP: ₹4,497)  Pack Of 6: ₹7,650 (MRP: ₹8,994)  Regulatory Note:  Dosage should be administered as per individual requirements, starting with a low dose and  gradually adjusting under the supervision of a licensed medical practitioner to ensure safe and  effective use.  For Best Results: Chew slowly to allow better absorption.  New to Cannabinoids? Start with a low dose and increase gradually as per your comfort and  response.  Product Name:  Cannabis Pain Relief Topical Oil  Formulation Overview:  Crafted for effective, localized relief, Cannacraft Cannabis Pain Relief Topical is a  fast-absorbing, non-greasy formulation designed to work beneath the skin for targeted support.  It is a plant-based Ayurvedic formulation.  Key Ingredients:  Vijaya leaf extract  Hemp Seed Oil  Camphor  Peppermint  Eucalyptus  Mechanism & Benefits:  Provides effective, localized relief.  Fast-absorbing and non-greasy.  Works beneath the skin for targeted support.  Offers a dual-action effect: warming sensation to enhance circulation and a cooling effect to  ease discomfort.  Nourishes and hydrates the skin while promoting deep relief.  Offers a safe, natural, and effective alternative for non-invasive, prescription-free support.  Ensures soothing comfort and enhanced mobility.  Delivery Technology:'}]

In [ ]:
#Data Visualization in tabular form.
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentance_count_raw,page_token_count,text
0,0,1258,190,2,314.50,Product Name: Klik – Full Spectrum Extract F...
1,1,1215,195,3,303.75,Prescription-only product Use strictly under ...
2,2,1205,204,5,301.25,Post-Workout Recovery Mild Inflammatory Cond...
3,3,1425,230,13,356.25,Crafted for those who need more from plant-bas...
4,4,1657,233,12,414.25,Topical oil Usage Suitability: Ideal solutio...

In [ ]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentance_count_raw,page_token_count
count,8.00,8.00,8.00,8.00,8.00
mean,3.50,1340.25,203.12,9.75,335.06
std,2.45,319.71,39.75,5.68,79.93
min,0.00,786.00,122.00,2.00,196.50
25%,1.75,1212.50,193.75,4.50,303.12
50%,3.50,1292.00,200.50,11.50,323.00
75%,5.25,1483.00,230.75,13.50,370.75
max,7.00,1850.00,254.00,17.00,462.50

In [ ]:
#Data Visualization in tabular form.
import pandas as pd

df = pd.DataFrame(pages_and_texts)
display(df.head())

,page_number,page_char_count,page_word_count,page_sentance_count_raw,page_token_count,text
0,0,1258,190,2,314.50,Product Name: Klik – Full Spectrum Extract F...
1,1,1215,195,3,303.75,Prescription-only product Use strictly under ...
2,2,1205,204,5,301.25,Post-Workout Recovery Mild Inflammatory Cond...
3,3,1425,230,13,356.25,Crafted for those who need more from plant-bas...
4,4,1657,233,12,414.25,Topical oil Usage Suitability: Ideal solutio...

### Further Text processing (Splitting Pages into sentences)
Two way to do this
1. We've done this by splitting on "." " " .
2. We can do this with a NLP library such as spaCy and nltk.

In [ ]:
from spacy.lang.en import English

nlp = English()

nlp.add_pipe("sentencizer")

doc = nlp("This is a sentence. This is another sentence. I Like elephants.")
assert len(list(doc.sents)) == 3

list (doc.sents)

[This is a sentence., This is another sentence., I Like elephants.]

In [ ]:
pages_and_texts[1]

{'page_number': 1,
 'page_char_count': 1215,
 'page_word_count': 195,
 'page_sentance_count_raw': 3,
 'page_token_count': 303.75,
 'text': 'Prescription-only product  Use strictly under supervision of a licensed medical practitioner  Product Name:  Pain Relief Mild Capsules  Formulation Overview:  A mild yet effective formulation designed for daily wellness support, containing 50mg of Vijaya  extract carefully blended with Ayurvedic ingredients.  Key Ingredients:  Vijaya extract (50mg)  Amla  Piperine  Mechanism & Benefits:  Assists in reducing inflammation  Promotes relaxation  Supports overall balance and general well-being  Helps manage chronic discomfort  Aids in stress regulation  Relieves muscle tension  May assist as a period aid (easing menstrual discomfort and cramping)  Supports the body’s natural inflammatory response  Offers a holistic and well-tolerated plant-based solution  Delivery Technology:  Capsule format, designed for structured use without disrupting daily activities.  Usage Suitability:  Ideal for:   Individuals seeking a gentle therapeutic approach   Managing chronic discomfort   Stress regulation   Muscle tension   General well-being   Period aid (easing menstrual discomfort and cramping)  Also suitable for:   Everyday Aches and Pains   Joint Pain and Stiffness   Stress-Related Muscle Tension   Headache Relief'}

In [ ]:
!pip install tqdm --upgrade

Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.66.2)
Collecting tqdm
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 2.4 MB/s eta 0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 3.4 MB/s eta 0:00:00
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.66.2
    Uninstalling tqdm-4.66.2:
      Successfully uninstalled tqdm-4.66.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.19 requires torch<2.7,>=1.10, but you have torch 2.7.1 which is incompatible.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2025.7.0 which is incompatible.
datasets 4.0.0 requires requests>=2.32.2, but you have requests 2.31.0 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.2.1 which is incompatible.
Successfully installed tqdm-4.67.1

In [ ]:
from tqdm.auto import tqdm
from tqdm import tqdm
import time

for item in tqdm(pages_and_texts):
  item["sentences"] = list(nlp(item["text"]).sents)

  #make sure all sentences are strings
  item["sentences"] = [str(sentence) for sentence in item["sentences"]]

  # Count the sentences
  item["page_sentence_count_spacy"] = len(item["sentences"])

100%|██████████| 8/8 [00:00<00:00, 211.38it/s]

In [ ]:
random.sample(pages_and_texts, k=1)

[{'page_number': 0,
  'page_char_count': 1258,
  'page_word_count': 190,
  'page_sentance_count_raw': 2,
  'page_token_count': 314.5,
  'text': 'Product Name:  Klik – Full Spectrum Extract  Formulation Overview:  A specialized medicinal formulation crafted using Ayurvedic principles, combining the full  therapeutic potential of Vijaya extract with other natural constituents.  Key Ingredients:  Vijaya Extract (Cannabis sativa full-spectrum)  (Other supporting actives not explicitly listed but aligned with Ayurvedic formulations)  Mechanism & Benefits:  Designed to support chronic discomfort, inflammatory conditions, and stress-related symptoms  Helps regulate sleep cycles  Aids in relaxation and emotional balance  Offers long-term wellness support through controlled dosing  Delivery Technology:  Utilizes Klik Dispense Technology – an oral syringe system for precise, single-dose  administration  Ensures measured and structured usage, especially for individuals requiring medical  supervision  Usage Suitability:  Ideal for:   Individuals with persistent physical discomfort   Stress and anxiety management   Sleep irregularities   Chronic inflammation  Also suitable for:   Regulated wellness routines   Long-term therapeutic use under guidance  Available Variants & Pricing:  Single Pack (1000μl): ₹2,599  Pack of 3: ₹7,020 (MRP: ₹7,797)  Pack of 6: ₹13,260 (MRP: ₹15,594)  Regulatory Note:',
  'sentences': ['Product Name:  Klik – Full Spectrum Extract  Formulation Overview:  A specialized medicinal formulation crafted using Ayurvedic principles, combining the full  therapeutic potential of Vijaya extract with other natural constituents.',
   ' Key Ingredients:  Vijaya Extract (Cannabis sativa full-spectrum)  (Other supporting actives not explicitly listed but aligned with Ayurvedic formulations)  Mechanism & Benefits:  Designed to support chronic discomfort, inflammatory conditions, and stress-related symptoms  Helps regulate sleep cycles  Aids in relaxation and emotional balance  Offers long-term wellness support through controlled dosing  Delivery Technology:  Utilizes Klik Dispense Technology – an oral syringe system for precise, single-dose  administration  Ensures measured and structured usage, especially for individuals requiring medical  supervision  Usage Suitability:  Ideal for:   Individuals with persistent physical discomfort   Stress and anxiety management   Sleep irregularities   Chronic inflammation  Also suitable for:   Regulated wellness routines   Long-term therapeutic use under guidance  Available Variants & Pricing:  Single Pack (1000μl): ₹2,599  Pack of 3: ₹7,020 (MRP: ₹7,797)  Pack of 6: ₹13,260 (MRP: ₹15,594)  Regulatory Note:'],
  'page_sentence_count_spacy': 2}]

In [ ]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentance_count_raw,page_token_count,page_sentence_count_spacy
count,8.00,8.00,8.00,8.00,8.00,8.00
mean,3.50,1340.25,203.12,9.75,335.06,9.88
std,2.45,319.71,39.75,5.68,79.93,5.77
min,0.00,786.00,122.00,2.00,196.50,2.00
25%,1.75,1212.50,193.75,4.50,303.12,4.50
50%,3.50,1292.00,200.50,11.50,323.00,11.50
75%,5.25,1483.00,230.75,13.50,370.75,14.25
max,7.00,1850.00,254.00,17.00,462.50,17.00

# Some time if you are facing issue with the progress bar from tqdm library you can use this code

In [ ]:
from tqdm.auto import tqdm
from tqdm import tqdm
import time

for i in tqdm(range(100), desc="Processing"):
    time.sleep(0.01)

Processing: 100%|██████████| 100/100 [00:01<00:00, 97.15it/s]

In [ ]:
# Define Split Size to turn groups of sentences into chunks
num_sentence_chunk_size = 10

# Create a Function to split lists of texts recursively into chunk size
# e.g. [20] -> [10, 10] or [25] -> [10, 10, 5]
def split_list(input_list: list[str],
              slice_size: int=num_sentence_chunk_size) -> list[list[str]]:
          return [input_list[i:i+slice_size] for i in range(0, len(input_list), slice_size)]
test_list = list (range(25))
split_list(test_list)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [ ]:
# Loop through pages and texts and split sentences into chunks
for item in tqdm(pages_and_texts):
  item["sentences_chunks"] = split_list(input_list=item["sentences"],
                                        slice_size=num_sentence_chunk_size)
  item["num_chunks"] = len(item["sentences_chunks"])

100%|██████████| 8/8 [00:00<00:00, 32017.59it/s]

In [ ]:
random.sample(pages_and_texts, k=1)

[{'page_number': 3,
  'page_char_count': 1425,
  'page_word_count': 230,
  'page_sentance_count_raw': 13,
  'page_token_count': 356.25,
  'text': 'Crafted for those who need more from plant-based relief  Available Variants & Pricing:  Single Pack: ₹1,499  Pack Of 3: ₹4,050 (MRP: ₹4,497)  Pack Of 6: ₹7,650 (MRP: ₹8,994)  Regulatory Note:  Dosage should be administered as per individual requirements, starting with a low dose and  gradually adjusting under the supervision of a licensed medical practitioner to ensure safe and  effective use.  For Best Results: Chew slowly to allow better absorption.  New to Cannabinoids? Start with a low dose and increase gradually as per your comfort and  response.  Product Name:  Cannabis Pain Relief Topical Oil  Formulation Overview:  Crafted for effective, localized relief, Cannacraft Cannabis Pain Relief Topical is a  fast-absorbing, non-greasy formulation designed to work beneath the skin for targeted support.  It is a plant-based Ayurvedic formulation.  Key Ingredients:  Vijaya leaf extract  Hemp Seed Oil  Camphor  Peppermint  Eucalyptus  Mechanism & Benefits:  Provides effective, localized relief.  Fast-absorbing and non-greasy.  Works beneath the skin for targeted support.  Offers a dual-action effect: warming sensation to enhance circulation and a cooling effect to  ease discomfort.  Nourishes and hydrates the skin while promoting deep relief.  Offers a safe, natural, and effective alternative for non-invasive, prescription-free support.  Ensures soothing comfort and enhanced mobility.  Delivery Technology:',
  'sentences': ['Crafted for those who need more from plant-based relief  Available Variants & Pricing:  Single Pack: ₹1,499  Pack Of 3: ₹4,050 (MRP: ₹4,497)  Pack Of 6: ₹7,650 (MRP: ₹8,994)  Regulatory Note:  Dosage should be administered as per individual requirements, starting with a low dose and  gradually adjusting under the supervision of a licensed medical practitioner to ensure safe and  effective use.',
   ' For Best Results: Chew slowly to allow better absorption.',
   ' New to Cannabinoids?',
   'Start with a low dose and increase gradually as per your comfort and  response.',
   ' Product Name:  Cannabis Pain Relief Topical Oil  Formulation Overview:  Crafted for effective, localized relief, Cannacraft Cannabis Pain Relief Topical is a  fast-absorbing, non-greasy formulation designed to work beneath the skin for targeted support.',
   ' It is a plant-based Ayurvedic formulation.',
   ' Key Ingredients:  Vijaya leaf extract  Hemp Seed Oil  Camphor  Peppermint  Eucalyptus  Mechanism & Benefits:  Provides effective, localized relief.',
   ' Fast-absorbing and non-greasy.',
   ' Works beneath the skin for targeted support.',
   ' Offers a dual-action effect: warming sensation to enhance circulation and a cooling effect to  ease discomfort.',
   ' Nourishes and hydrates the skin while promoting deep relief.',
   ' Offers a safe, natural, and effective alternative for non-invasive, prescription-free support.',
   ' Ensures soothing comfort and enhanced mobility.',
   ' Delivery Technology:'],
  'page_sentence_count_spacy': 14,
  'sentences_chunks': [['Crafted for those who need more from plant-based relief  Available Variants & Pricing:  Single Pack: ₹1,499  Pack Of 3: ₹4,050 (MRP: ₹4,497)  Pack Of 6: ₹7,650 (MRP: ₹8,994)  Regulatory Note:  Dosage should be administered as per individual requirements, starting with a low dose and  gradually adjusting under the supervision of a licensed medical practitioner to ensure safe and  effective use.',
    ' For Best Results: Chew slowly to allow better absorption.',
    ' New to Cannabinoids?',
    'Start with a low dose and increase gradually as per your comfort and  response.',
    ' Product Name:  Cannabis Pain Relief Topical Oil  Formulation Overview:  Crafted for effective, localized relief, Cannacraft Cannabis Pain Relief Topical is a  fast-absorbing, non-greasy formulation designed to work beneath the skin for targeted support.',
    ' It is a plant-based Ayurvedic formulation.',
    ' Key Ingredients:  Vijaya leaf extract  Hemp Seed Oil  Camphor  Peppermint  Eucalyptus  Mechanism & Benefits:  Provides effective, localized relief.',
    ' Fast-absorbing and non-greasy.',
    ' Works beneath the skin for targeted support.',
    ' Offers a dual-action effect: warming sensation to enhance circulation and a cooling effect to  ease discomfort.'],
   [' Nourishes and hydrates the skin while promoting deep relief.',
    ' Offers a safe, natural, and effective alternative for non-invasive, prescription-free support.',
    ' Ensures soothing comfort and enhanced mobility.',
    ' Delivery Technology:']],
  'num_chunks': 2}]

In [ ]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentance_count_raw,page_token_count,page_sentence_count_spacy,num_chunks
count,8.00,8.00,8.00,8.00,8.00,8.00,8.00
mean,3.50,1340.25,203.12,9.75,335.06,9.88,1.62
std,2.45,319.71,39.75,5.68,79.93,5.77,0.52
min,0.00,786.00,122.00,2.00,196.50,2.00,1.00
25%,1.75,1212.50,193.75,4.50,303.12,4.50,1.00
50%,3.50,1292.00,200.50,11.50,323.00,11.50,2.00
75%,5.25,1483.00,230.75,13.50,370.75,14.25,2.00
max,7.00,1850.00,254.00,17.00,462.50,17.00,2.00

In [ ]:
import re

# Split each chunks into its own item
pages_and_chunks = []
for item in tqdm(pages_and_texts):
  for sentence_chunk in item["sentences_chunks"]:
    chunk_dict={}
    chunk_dict["page_number"] = item["page_number"]
    # Join the senteces together into a paragraph-like structure, aka join the list of sentences into one paragraphs
    joined_sentence_chunk = "".join(sentence_chunk).replace(" "," ").strip()
    joined_sentence_chunk = re.sub(r'\.([A-Z])',r'.\1', joined_sentence_chunk) # ".A" => ". A" (Will work for any capital Letter)

    chunk_dict["sentence_chunk"] = joined_sentence_chunk

    # Get Some stats on our chunks
    chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
    chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
    chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4 # 1 token = ~4 chars.

    pages_and_chunks.append(chunk_dict)

len(pages_and_chunks)

100%|██████████| 8/8 [00:00<00:00, 7681.88it/s]

13

In [ ]:
random.sample(pages_and_chunks, k=1)

[{'page_number': 1,
  'sentence_chunk': 'Prescription-only product  Use strictly under supervision of a licensed medical practitioner  Product Name:  Pain Relief Mild Capsules  Formulation Overview:  A mild yet effective formulation designed for daily wellness support, containing 50mg of Vijaya  extract carefully blended with Ayurvedic ingredients. Key Ingredients:  Vijaya extract (50mg)  Amla  Piperine  Mechanism & Benefits:  Assists in reducing inflammation  Promotes relaxation  Supports overall balance and general well-being  Helps manage chronic discomfort  Aids in stress regulation  Relieves muscle tension  May assist as a period aid (easing menstrual discomfort and cramping)  Supports the body’s natural inflammatory response  Offers a holistic and well-tolerated plant-based solution  Delivery Technology:  Capsule format, designed for structured use without disrupting daily activities. Usage Suitability:  Ideal for:   Individuals seeking a gentle therapeutic approach   Managing chronic discomfort   Stress regulation   Muscle tension   General well-being   Period aid (easing menstrual discomfort and cramping)  Also suitable for:   Everyday Aches and Pains   Joint Pain and Stiffness   Stress-Related Muscle Tension   Headache Relief',
  'chunk_char_count': 1213,
  'chunk_word_count': 193,
  'chunk_token_count': 303.25}]

In [ ]:
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count        13.00             13.00             13.00              13.00
mean          4.08            818.92            119.54             204.73
std           2.22            497.65             76.05             124.41
min           0.00             50.00              6.00              12.50
25%           3.00            532.00             63.00             133.00
50%           4.00            779.00            120.00             194.75
75%           6.00           1201.00            189.00             300.25
max           7.00           1595.00            216.00             398.75

# Filter Chunks of text for short chunks
These chunks may not contain much information

In [ ]:
# Show random chunks with under 30 tokens in Length
min_token_length = 30
for row in df[df["chunk_token_count"] <= min_token_length].sample(2).iterrows():
  print(f'Chunk token count : {row[1]["chunk_token_count"]}| Text: {row[1]["sentence_chunk"]}')

  # in my case i have only two result which matter for me.

Chunk token count : 12.5| Text: Enhances joint flexibility. Promotes nerve health.
Chunk token count : 19.0| Text: The product is described as "plant-based" and offering "Ayurvedic wellness."

In [ ]:
# Fillter our DataFrame for rows with under 30 tokens
#pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")

# Returns first 2 records from the filtered list.
#pages_and_chunks_over_min_token_len[:2]

[{'page_number': 0,
  'sentence_chunk': 'Product Name:  Klik – Full Spectrum Extract  Formulation Overview:  A specialized medicinal formulation crafted using Ayurvedic principles, combining the full  therapeutic potential of Vijaya extract with other natural constituents. Key Ingredients:  Vijaya Extract (Cannabis sativa full-spectrum)  (Other supporting actives not explicitly listed but aligned with Ayurvedic formulations)  Mechanism & Benefits:  Designed to support chronic discomfort, inflammatory conditions, and stress-related symptoms  Helps regulate sleep cycles  Aids in relaxation and emotional balance  Offers long-term wellness support through controlled dosing  Delivery Technology:  Utilizes Klik Dispense Technology – an oral syringe system for precise, single-dose  administration  Ensures measured and structured usage, especially for individuals requiring medical  supervision  Usage Suitability:  Ideal for:   Individuals with persistent physical discomfort   Stress and anxiety management   Sleep irregularities   Chronic inflammation  Also suitable for:   Regulated wellness routines   Long-term therapeutic use under guidance  Available Variants & Pricing:  Single Pack (1000μl): ₹2,599  Pack of 3: ₹7,020 (MRP: ₹7,797)  Pack of 6: ₹13,260 (MRP: ₹15,594)  Regulatory Note:',
  'chunk_char_count': 1257,
  'chunk_word_count': 189,
  'chunk_token_count': 314.25},
 {'page_number': 1,
  'sentence_chunk': 'Prescription-only product  Use strictly under supervision of a licensed medical practitioner  Product Name:  Pain Relief Mild Capsules  Formulation Overview:  A mild yet effective formulation designed for daily wellness support, containing 50mg of Vijaya  extract carefully blended with Ayurvedic ingredients. Key Ingredients:  Vijaya extract (50mg)  Amla  Piperine  Mechanism & Benefits:  Assists in reducing inflammation  Promotes relaxation  Supports overall balance and general well-being  Helps manage chronic discomfort  Aids in stress regulation  Relieves muscle tension  May assist as a period aid (easing menstrual discomfort and cramping)  Supports the body’s natural inflammatory response  Offers a holistic and well-tolerated plant-based solution  Delivery Technology:  Capsule format, designed for structured use without disrupting daily activities. Usage Suitability:  Ideal for:   Individuals seeking a gentle therapeutic approach   Managing chronic discomfort   Stress regulation   Muscle tension   General well-being   Period aid (easing menstrual discomfort and cramping)  Also suitable for:   Everyday Aches and Pains   Joint Pain and Stiffness   Stress-Related Muscle Tension   Headache Relief',
  'chunk_char_count': 1213,
  'chunk_word_count': 193,
  'chunk_token_count': 303.25}]

# Embeding
-> Allow you to convert text into number and number are more understandable in ai.

In [ ]:
# This allow use to install requirement file for python
!pip install --upgrade --force-reinstall numpy
!pip install --upgrade sentence-transformers

Collecting numpy
  Downloading numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 1.9 MB/s eta 0:00:00
Downloading numpy-2.3.2-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 74.6 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.2
    Uninstalling numpy-2.3.2:
      Successfully uninstalled numpy-2.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.8.3 requires numpy<2,>=1.21, but you have numpy 2.3.2 which is incompatible.
google-colab 1.0.0 requires ipykernel==6.17.1, but you have ipykernel 6.30.0 which is incompatible.
google-colab 1.0.0 requires ipython==7.34.0, but you have ipython 9.4.0 which is incompatible.
google-colab 1.0.0 requires notebook==6.5.7, but you have notebook 7.4.4 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.1 which is incompatible.
google-colab 1.0.0 requires requests==2.32.3, but you have requests 2.32.4 which is incompatible.
google-colab 1.0.0 requires tornado==6.4.2, but you have tornado 6.5.1 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
cupy-cuda12x 13.3.0 requires numpy<2.3,>=1.22, but you have numpy 2.3.2 which is incompatible.
fastai 2.7.19 requires torch<2.7,>=1.10, but you have torch 2.7.1 which is incompatible.
torchvision 0.21.0+cu124 requires torch==2.6.0, but you have torch 2.7.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.3.2 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.1 which is incompatible.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2025.7.0 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.3.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.2.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.2 which is incompatible.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
bigframes 2.12.0 requires rich<14,>=12.4.4, but you have rich 14.1.0 which is incompatible.
Successfully installed numpy-2.3.2

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (5.0.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.54.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.7.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.34.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.7.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.5)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.11.1.6)
Requirement already satisfied: triton==3.3.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.3.1)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/lib/python3.11/dist-packages (from triton==3.3.1->torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.3.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.7.34)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.7.14)

KeyboardInterrupt:

In [ ]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer(model_name_or_path= "all-mpnet-base-v2",
                                      device="cpu")
# Create a list of sentences
sentences = ['This framework generates embeddings for each input sentence',
             'Sentences are passed as a list of string.',
             'The quick brown fox jumps over the lazy dog.']

# Sentences are encoded/embedded by calling model.encode()
embeddings = embedding_model.encode(sentences)
embedding_dict = dict(zip(sentences, embeddings))

# See the embeddings
for sentece, embedding in embedding_dict.items():
  print(f"Sentence: {sentece}")
  print(f"Embedding: {embedding}")
  print("")

ImportError: cannot import name '_center' from 'numpy._core.umath' (/usr/local/lib/python3.11/dist-packages/numpy/_core/umath.py)

In [ ]:
embeddings[0].shape

In [ ]:
%% time
embedding_model.to("cpu")

# Embed each chunk one by one.
for item in tqdm(pages_and_chunks):
  item["embedding"] = embedding_model.encode(item["sentence_chunk"])